services:
  embyx:
    image: ghcr.io/juneix/embyx:latest
    container_name: embyx
    restart: unless-stopped
    network_mode: host
    environment:
      - APP_LANG=zh # zh (中文), en (English)
      - APP_PORT=8090 # 访问端口 (Access Port)
