version: '3.8'

services:
  embyx-local:
    image: registry.cn-shenzhen.aliyuncs.com/sliwei/embyx-local:${TAG}
    container_name: embyx-local
    restart: always
    # ports:
    #   - "8090:8090"
    volumes:
      - /vol2/1000/movie/短剧/11731-出山（70集）:/media
      - ./data:/data
    environment:
      - NODE_ENV=production
      - PORT=8090
      - MEDIA_ROOTS=/media
      - DB_PATH=/data/app.db
      - CACHE_DIR=/data/cache
      - FFMPEG_CONCURRENCY=3
      - SCAN_INTERVAL_MS=600000
    networks:
      - proxy

networks:
  proxy:
    external: true